[package]
name = "actionkv"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.2"
crc = "1.7"
serde_derive = "1.0.136"
serde = { version = "1.0.136", features = ["derive"]}

[lib]
name = "libactionkv"
path = "src/lib.rs"

[[bin]]
name = "akv_mem"
path = "src/akv_mem.rs"